### ISSUE TITLE
Mailing List

### ISSUE THREAD

**Issue by j0sh** [afrind/draft-rush#3]
Excited for this project, looking forward to discussing it. Seems that the mailing list in the [contribution guidelines](https://github.com/afrind/draft-rush/blob/main/CONTRIBUTING.md) doesn't exist?

**Comment by afrind** [comment]
Oops - I think the template generated that automatically.  Right now I emailed a few different IETF lists to gauge interest, looks like the discussion may be happening in avtcore for now.  I'll update the doc to reflect that.
