### ISSUE TITLE
Discussing venues

### ISSUE THREAD

**Issue by SpencerDawkins** [afrind/draft-rush#6]
From IESG/IAB feedback: 

> Should some of this work go to ART and some of it go to TSV? Or should we have one single effort that takes up both parts of what you're proposing?

I agree that this matters, but
- this needs to take a back seat to the first three BOF goals. 
- it might be useful to add a new section/subsection as "Post-BoF Goals", and put "determining existing working groups" and "determine appropriate area(s)" there. I can't speak for anyone on the IESG, but I'd expect that talking about technical considerations is an appropriate use of face-to-face-to-virtual-face time, and talking about administrative minutia is better handed to (the MOQ) mailing list. 

Want me to do a PR on this?

**Comment by afrind** [comment]
Moved to https://github.com/afrind/moqbof/issues/1

Can you restate your comment there?  And sure, happy to take a PR!
